version: '3.7'

services:
  web:
    build: ./docker_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./docker_app/:/usr/src/docker_app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=1234567816
      - POSTGRES_DB=docker_app

volumes:
  postgres_data: